### ISSUE TITLE
Support generating structs only, without package decleration. 

### ISSUE THREAD

**Issue by meblum** [twpayne/go-xmlstruct#18]
An empty string as package name should be treated as a "no-package" remove the `package ...` line.

**Comment by twpayne** [comment]
If there is no `package` line then the output is not a valid Go source file. See https://go.dev/ref/spec#Source_file_organization.

**Comment by meblum** [comment]
Right, I'd like to append the output to an existing go file.

**Comment by twpayne** [comment]
OK, but why append? What is the specific case where multiple source files does not work?

**Comment by meblum** [comment]
Say I have an existing go file and I just need to add a few types. Currently I'd need to manually strip the package declaration.

Happy to submit a PR

**Comment by twpayne** [comment]
> Say I have an existing go file and I just need to add a few types. Currently I'd need to manually strip the package declaration.

In this case the few types can be added in a separate Go source file in the same package.

What is your specific workflow that requires appending? Note that:

* Appending breaks idempotency, as you always append type definitions rather than replacing previous type definitions, which leads to invalid files as the same type will be defined multiple times.

* Appending is not compatible with `//go:generate`. go-xmlstruct is designed to work with `//go:generate`.

**Comment by meblum** [comment]
> In this case the few types can be added in a separate Go source file in the same package.

I don't like separating the types from the function that use them.

> What is your specific workflow that requires appending?

I have an existing package where I want to add some type. It's a one-time addition, not based on a ci/cd workflow.

> Appending is not compatible with //go:generate.

Omitting the package line where en empty string is supplied as the package name is not a breaking change, as currently it will output just "package" which is not valid either.

**Comment by twpayne** [comment]
> Omitting the package line where en empty string is supplied as the package name is not a breaking change, as currently it will output just "package" which is not valid either.

Good point. OK happy to accept a PR for this :)

**Comment by twpayne** [comment]
Thanks for the PRs. I've pushed a new version with tag `v1.2.0` which includes these and a fix for #21.

**Comment by meblum** [comment]
Thank, to you! Appreciate it.
