### ISSUE TITLE
handling custom entities

### ISSUE THREAD

**Issue by alaa2amz** [twpayne/go-xmlstruct#24]
**first, thanks for this great work.**
_second, let's get into issue_
when I tried to generate structs from japanese xml dictionary

-    link: ftp://ftp.edrdg.org/pub/Nihongo//JMdict.gz
-    page: https://www.edrdg.org/jmdict/j_jmdict.html

then
  ```
$gunzip JMdict.gz
  $cat JMdict |goxmlstruct
```
I got this error
 ` XML syntax error on line 528: invalid character entity &unc;`
the reason this xml is defining custom entities
in file begining dtd you will find line
`<!ENTITY unc "unclassified">`
the solution is as the in link
https://stackoverflow.com/questions/28662417/go-xml-error-invalid-character-entity
the suggestion is add dtd scanning to define custom entities
thanks in advance

**Comment by twpayne** [comment]
Thanks for the kind words and thanks for the suggestion and thanks for the research into the solution.

#25 adds a generic mechanism to modify the `encoding/xml.Decoder` before it is used, which can be used to set the decoder's `Entity` field. It includes an example that generates a Go struct from `JMdict.gz`. See the PR for more details.

Note that `JMdict.gz` contains a repeated `ENTITY` declaration for `ik` which you can see with:

```console
$ zgrep -n 'ENTITY ik ' JMdict.gz
358:<!ENTITY ik "word containing irregular kana usage">
515:<!ENTITY ik "word containing irregular kana usage">
```

Perhaps you could report this to the maintainers of JMdict.

**Comment by twpayne** [comment]
> the suggestion is add dtd scanning to define custom entities

Note that if you have the DTD then the DTD defines the structure of the XML document, so you can generate the Go struct from the DTD and don't need go-xmlstruct at all.

**Comment by alaa2amz** [comment]
Thanks you very much for the reply.
I am sorry that I didn't read previous issues before making new one.
I am happy that the issue handled already.
I will try it.
Thanks again for your help and kind reply.

**Comment by twpayne** [comment]
> I am sorry that I didn't read previous issues before making new one.

You did read the previous issues - I created #25 in response to you opening this one. You found a genuine missing feature in go-xmlstruct and thanks to your work everyone will benefit!

I've just tagged go-xmlstruct `v1.4.0` which includes #25.
