### ISSUE TITLE
feat: option to generate unexported types

### ISSUE THREAD

**Issue by meblum** [twpayne/go-xmlstruct#36]
The `WithExportNameFunc` will modify the struct type names _and_  the struct fields. This is a problem when you want to modify the types to be unexported as the fields will be unexported as well. Fields must be exported in order to be processed by `encoding/xml`.

**Comment by twpayne** [comment]
I don't understand what you are asking. Could you give a concrete example that demonstrates the current behavior and the behavior you want?

**Comment by meblum** [comment]
I don't want to export the generated types. Given `<a><b><c></c></b></a>` I'd like to generate
```go
type a struct {
        B b `xml:"b"`
}

type b struct {
        C struct{} `xml:"c"`
}
```
instead of
```go
type A struct {
        B B `xml:"b"`
}

type B struct {
        C struct{} `xml:"c"`
}
```

**Comment by meblum** [comment]
Do at first I thought of creating the  following function and use `WithExportNameFunc`, but then I realized that this will unexport the struct fields as well.

```go
// DefaultUnexportNameFunc returns name.Local with kebab- and snakecase words
// converted to lowerCamelCase and any Id suffix converted to ID.
DefaultUnexportNameFunc = func(name xml.Name) string {
	localName := kebabOrSnakeCaseWordBoundaryRx.ReplaceAllStringFunc(name.Local, func(s string) string {
		return strings.ToUpper(s[len(s)-1:])
	})
	localName = nonIdentifierRuneRx.ReplaceAllLiteralString(localName, "_")
	runes := []rune(localName)
	runes[0] = unicode.ToLower(runes[0])
	if len(runes) > 2 && runes[len(runes)-2] == 'I' && runes[len(runes)-1] == 'd' {
		runes[len(runes)-1] = 'D'
	}
	return string(runes)
}
```

**Comment by twpayne** [comment]
OK, thank you for the concrete example. That makes things clear.

How about putting the generated code in an `internal` module instead? This way you can still use the generated types without exporting them.

**Comment by meblum** [comment]
That could work, but I wouldn't create an internal package just because of this. I can rename them by hand, but I think having an option for this makes sense.

**Comment by meblum** [comment]
In the meantime it can be done by using something like
```
goxmlstruct | sed -E 's/type ([A-Z])/\L&/'
```

**Comment by meblum** [comment]
@twpayne submitted a pull request that adds a `WithExportTypeNameFunc` option and a corresponding  `--no-export` cli flag.

**Comment by twpayne** [comment]
I've tagged `v1.7.0` which includes this.

**Comment by meblum** [comment]
Thank you!
