### ISSUE TITLE
Using `WithExportNameFunc` will cause `WithExportRenames` to be ignored

### ISSUE THREAD

**Issue by meblum** [twpayne/go-xmlstruct#37]
[playground](https://go.dev/play/p/y4iuD7WXavX)

Setting
```go
 xmlstruct.NewGenerator(
	xmlstruct.WithExportNameFunc(xmlstruct.DefaultExportNameFunc),
	xmlstruct.WithExportRenames(map[string]string{"a": "Foo"}),
)
```

And testing on `<a/><b/>` outputs `type A struct{} type B struct{}` instead of `type Foo struct{} type B struct{}`

**Comment by meblum** [comment]
Not currently using `WithExportRenames`, just bumped into this while looking at https://github.com/twpayne/go-xmlstruct/issues/36

**Comment by meblum** [comment]
Actually, I'm not sure what the correct behavior would be in this case. Perhaps returning an error from NewGenerator makes the most sense?

**Comment by twpayne** [comment]
`WithExportRenames` is a shortcut for setting `WithExportNameFunc` for common, simple cases. I've updated the documentation to state this in #39.
