### ISSUE TITLE
Add support for overriding types of specific fields

### ISSUE THREAD

**Issue by twpayne** [twpayne/go-xmlstruct#4]
Suggested by @mgeisler:

It should be possible to override go-xmlstruct's automatic type detection for specific fields.

**Comment by meblum** [comment]
I think the most common use case would be to have `string` instead of `struct{}` for empty elements, as an empty element may still optionally have some text. Would it make sense to add an option for this?

**Comment by twpayne** [comment]
I'd definitely consider a PR that adds a `-no-empty-elements` flag that has this effect.

**Comment by twpayne** [comment]
Closing this as what is already implemented seems sufficient for now.
