### ISSUE TITLE
Generate compact types

### ISSUE THREAD

**Issue by meblum** [twpayne/go-xmlstruct#41]
The following xml `<a><b><c><d><e></e></d></c></b></a>`  will generate
```go
type A struct {
        B struct {
                C struct {
                        D struct {
                                E struct{} `xml:"e"`
                        } `xml:"d"`
                } `xml:"c"`
        } `xml:"b"`
}
```

But it can be simplified to just
```go
type A struct {
	E struct{} `xml:"b>c>d>e"`
}
```

**Comment by meblum** [comment]
Would love to just submit a PR for this, but it feels quite complicated to implement and I currently don't have the time.

**Comment by twpayne** [comment]
I don't think this is a good idea as it loses the structure of the XML document.

The two examples you give are not equivalent. In the first example you access the value of `E` by writing `A.B.C.D.E` whereas in the second example you would write `A.E`.

**Comment by meblum** [comment]
> In the first example you access the value of E by writing A.B.C.D.E whereas in the second example you would write A.E.

That's exactly the point. When the xml representation is unnecessarily verbose, it's nice to at least have it compacted in code. Would you accept a PR for this if time permits in the future?

**Comment by twpayne** [comment]
OK, I'll accept a PR that adds an option to do this. However, I think losing the structural equivalence between the XML document and the Go types is a bad idea. For example, if any of the `b`, `c`, or `d` elements get a second child or element you'll have to rewrite your code.

**Comment by twpayne** [comment]
I've tagged `v1.8.0` which includes your PR. Thank you!
