### ISSUE TITLE
Add suppot for `go generate`

### ISSUE THREAD

**Issue by scirelli** [twpayne/go-xmlstruct#46]
Currently `goxmlstruct` only works on  a single file when using `go generate` to [generate](https://go.dev/blog/generate) code. 

For example this will not work because there's no shell expansion happening
```
//go:generate goxmlstruct -output somefile.go -package-name somepackage /path/to/xml/files/*.xml
```

It looks like there's already [code](https://github.com/twpayne/go-xmlstruct/blob/master/generator.go#L396) that can handle this. Maybe a new flag needs to be added for it?

**Comment by twpayne** [comment]
The issue here is that `*.xml` is expanded by the shell, but your `go:generate` comment invokes goxmlstruct directly, without invoking any shell.

Instead, you can probably use (warning: untested):

```go
//go:generate sh -c "goxmlstruct -output somefile.go -package-name somepackage /path/to/xml/files/*.xml"

**Comment by twpayne** [comment]
#47 adds a `--pattern` flag so you can use:

```go
//go:generate goxmlstruct -output somefile.go -package-name somepackage -pattern /path/to/xml/files/*.xml
```
