### ISSUE TITLE
Include schema data from XSD, if available

### ISSUE THREAD

**Issue by twpayne** [twpayne/go-xmlstruct#6]
Suggested by @yene.

If an XSD exists for the schema exists, we can mine it for type information, for example enums (#5). It would be great if go-xmlstruct could take an optional XSD as an argument.

**Comment by surfmuggle** [comment]
What do you suggest to do if one has only an xsd file as input to generate go structs?

**Comment by twpayne** [comment]
As the XSD contains the full schema, you can generate a Go struct from it directly, e.g. https://github.com/GoComply/xsd2go or https://github.com/xuri/xgen.
